# raise Exception
raise Exception('break out a exception')
